export const SKILL_SEARCH_DESC = [
  "【Relevance Search】Search skills by free-text query and return BM25-ranked hits.",
  "",
  "Use this when the user describes an intent or task in their own words and you ",
  "need to discover the most relevant skill(s) without scrolling the full catalog.",
  "Each hit carries a relevance score so you can decide whether to act on the top ",
  "result or ask a clarifying question.",
  "",
  "Usage:",
  "- skill_search({query: 'check broken images on a webpage'}) — top 10 hits",
  "- skill_search({query: '...', limit: 5}) — narrow the result",
  "- skill_search({query: '...', tags: ['analysis']}) — pre-filter by tag",
  "",
  "When to call skill_list vs skill_search:",
  "- Browsing / 'what's available' → skill_list",
  "- Specific user intent / 'I want to do X' → skill_search",
  "- skill_list({query: '...'}) is also valid as a shortcut",
].join("\n");

export const SKILL_LIST_DESC = [
  "【Must-Check Resource】List ALL available skills (built-in, plugin, and extension).",
  "",
  "MUST call this tool (do NOT skip) when:",
  "- User asks what skills/capabilities/tools are available",
  "- User asks to list, find, or discover skills",
  "- User asks to refresh or update skills list",
  "- User presents a task or goal (e.g., 'help me X', '完成XXX') that may require a skill",
  "- User asks what is installed in the system",
  "- User directly specifies a skill name or slug to use — call skill_list() first to verify skill exists",
  "- First conversation to learn what's available",
  "- Uncertain which skill to use — call skill_list() first",
  "",
  "Do NOT skip even if skills appear in system-reminder — ",
  "the system-reminder list may be incomplete. This tool returns to authoritative,",
  "complete skill catalog.",
  "",
  "Usage:",
  "- skill_list() — returns all skills",
  "- skill_list({tags: [\"tag1\", \"tag2\"]}) — filter by tags",
  "- skill_list({query: \"check broken links\"}) — return top-20 matches by relevance (BM25)",
  "",
  "Examples:",
  "- User: 'what skills are installed' → skill_list()",
  "- User: 'what can you do' → skill_list()",
  "- User: 'refresh skills' → skill_list()",
  "- User: 'help me fix this bug' → skill_list()",
  "- User: 'skills for code review' → skill_list({tags: [\"code-review\"]})",
  "- User: 'I want to scan a page for broken images' → skill_list({query: \"broken images\"})",
  "",
  "List format: - slug [id:uuid]: description. Use skill_view(slug) or skill_view(id) to load.",
].join("\n");

export const SKILL_VIEW_DESC = [
  "【Skill Entry】Load the full instructions (SKILL.md) for a specified skill.",
  "",
  "This is the only entry point for using any skill — you must call this tool first",
  "to get complete instructions, then follow the steps and constraints defined",
  "in the instructions strictly. Do not skip skill_view and guess skill content.",
  "",
  "After loading, if the instructions reference other files (references/, templates/, scripts/),",
  "use skill_file to batch-load them. Only call this tool after discovering relevant skills via skill_list.",
  "Supports skill_view(skill_slug) or skill_view(skill_id).",
].join("\n");

export const SKILL_FILE_DESC = [
  "【Auxiliary Files】Batch-read auxiliary files from a skill package (reference docs, templates, scripts, images, videos, etc.).",
  "",
  "Prerequisite: Must load the skill main file via skill_view first.",
  "Only call this tool when the skill instructions (SKILL.md) explicitly reference an auxiliary file.",
  "Do not proactively browse or guess files in the skill package — only load files mentioned in the main instructions.",
  "",
  "Supports passing multiple file paths for batch concurrent reading to reduce round trips.",
  "Supports skill_file(skill_slug, file_paths) or skill_file(skill_id, file_paths).",
  "Text files return content; images/videos return as base64.",
].join("\n");

export const SKILL_FEEDBACK_DESC = [
  "【Effect Feedback】After completing a task using a skill, call this tool to report the result.",
  "This helps improve skill quality and recommendation ranking. Report honestly.",
  "",
  "Example:",
  "skill_feedback({",
  "  skill_slug: \"product-analyzer\",",
  "  outcome: \"success\",",
  "  context: \"Analyzed product cache inconsistency issue\",",
  "  agent_comment: \"Skill steps were clear, successfully identified the problem\"",
  "})",
].join("\n");