-- P1-11 (stage 2a) — Persist retrieval signals on the skills row.
--
-- The manifest fields `triggers` / `when_to_use` / `embedding_text` (added in
-- stage 1) need a durable home so the BM25 indexer (stage 2b) and the
-- pluggable embedding provider (stage 3) can read them without re-parsing
-- SKILL.md on every server boot.
--
-- A single `retrieval_meta` JSON column was chosen over three separate
-- typed columns for two reasons:
--   1. Stage 3 will append more fields (e.g. embedding vector hash, model
--      version) — keeping them under one JSON envelope avoids a chain of
--      one-field migrations.
--   2. The fields are write-once-per-import and read by a small number of
--      ranking call sites; they don't need column-level indexing. BM25
--      scoring uses an inverted index (separate table in stage 2b), not
--      a SELECT WHERE on these columns.
--
-- Hydration tolerates corrupt JSON the same way `attributes` does: parse
-- failure logs at warn, bumps `skillRowJsonParseErrors{column="retrieval_meta"}`,
-- and yields {} so consumers see a Record<string, unknown> shape.
ALTER TABLE `skills` ADD COLUMN `retrieval_meta` text;
